package utils

import "regexp"

// Generated by AI.
func GetPasswordLevel(str string) int {
	if str == "" {
		return 0
	}
	length := len(str)

	matches := regexp.MustCompile(`^[a-zA-Z]+$`).MatchString(str)
	matches2 := regexp.MustCompile(`^\d+$`).MatchString(str)
	matches3 := regexp.MustCompile(`^[^0-9a-zA-Z]+$`).MatchString(str)
	matches4 := regexp.MustCompile(`[a-zA-Z]`).MatchString(str)
	matches5 := regexp.MustCompile(`[^a-zA-Z]`).MatchString(str)
	matches6 := regexp.MustCompile(`\d`).MatchString(str)
	matches7 := regexp.MustCompile(`[^\d]`).MatchString(str)

	if length > 0 {
		if length < 6 || (matches && length < 8) || matches2 || matches3 {
			return 1
		}
		if (!matches || length < 8) && !((matches4 && matches5 && length < 8) || (matches6 && matches7 && length < 8)) {
			if (matches4 && matches5 && length >= 8) || (matches6 && matches7 && length >= 8) {
				return 3
			}
			return 0
		}
		return 2
	}
	return 0
}
